<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2025-05-14T11:04:51+03:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Africa/Addis_Ababa',
    'theme_paths' => [
        '/account' => 'atomik',
        '/members/profile' => [
            'atomik',
            'profile.php',
        ],
    ],
    'api_keys' => [
        'google' => [
            'maps' => '',
        ],
    ],
];
