<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2025-04-14T19:49:56+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '9.4.0RC2',
    'version_db_installed' => '20250227155410',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1744652989,
    ],
    'email' => [
        'default' => [
            'address' => 'hadushtsigabu11@gmail.com',
        ],
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
    'security' => [
        'production' => [
            'mode' => 'development',
        ],
    ],
];
