<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2025-05-14T11:04:51+03:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '9.4.1',
    'version_db_installed' => '20250227155410',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1747209887,
    ],
    'email' => [
        'default' => [
            'address' => 'enbakomtsigabu@gmail.com',
        ],
    ],
    'security' => [
        'production' => [
            'mode' => 'development',
        ],
    ],
];
