<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2025-04-14T19:49:56+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.seo.canonical_url
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'TourGuide',
            'seo' => [
                'canonical_url' => 'http://localhost/open_Source_Computing/',
            ],
        ],
    ],
];
