<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2025-05-14T11:04:51+03:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'tigray tour guide',
        ],
    ],
];
